### PR TITLE
Canceled tool radius compensation and a drill bug fix.

### PR DESCRIPTION
**Pull request by ReeseWang**
Tool radius compensation is for hand-G-coding only, in my opinion. It would cause trouble in CAM if the tool table in CAM and Mach3 has diameter mismatch.

The drill bug is that Mach3 won't drill the hole inside G8x - G80 cycle if Z coordinate is specified.

Mach3 will drill (0,0) only if the Gcode is like below:

```
G0 X0 Y0 Z2
G81 Z-4 R2 F300
X10 Y0 Z2
X10 Y10 Z2
X0 Y10 Z2
G80
```

And if the code is like this, all 4 holes will be drilled:

```
G0 X0 Y0 Z2
G81 Z-4 R2 F300
X10 Y0
X10 Y10
X0 Y10
G80
```

### CODE REVIEW

**Comment by vakeiros** [comment]
question, when do you get those gcodes??? I'd tested MANY parts with this Post and no problems at all, and believe me I'd made lots of drilling testing with no problems. my gcode output of this post it's identical to your second example. I'd made about 50 parts requiring lot's of drills with this post and no problems at all, including auto recognition arround 4th axis and transformations also arround 4th axis.

so I don't know in what case do you get those gcodes, but yeah you're right about the Z inside the drill cycle, it won't work if it's there.

I've seen your changes on the post, the latest rev of the post is the PostDevTestMachine.gpp, all testing was made upon this Post, and the line you changed on it it's a comment (has the ";" on it so no chages at all there)

about the tool radius compensation I simply have no idea what that does so... but for sure it haven't given any problems to me. my parts are comming out great.

**Comment by teodoryantcheff** [comment]
Also, btw, pay attention only to the PostDevxxxx files as once complete I will replace the others with them.

**Comment by teodoryantcheff** [comment]
@vakeiros, can you confirm that 3 coord drill points don't work. IIRC, I specifically added the Z coord after we spent quite some time resolving your gazzilliion hole parts.. Just let me know, please.

**Comment by vakeiros** [comment]
@teodoryantcheff yeah using cycles the Z coord can't be there, Z it's entirely controlled by the cycle, BUT the Z wont appear on any of my drill programs, I can post a few programs generated by the post and you can see that's all right. like I said the line he changed on the PostDevTestMachine.gpp, line 372 I believe, it's a comment line: 
line 372 ";    {nb, ' ', ' X'xpos, ' Y'ypos, ' Z'zpos}"
so it won't change anything...

I would like to have access to the part @thuSkywalker is having problems, because like you know better than anyone else, we tested drilling A LOT to have it up and running.... we tested hole recognition arround Y cylinder, drilling transformations, plain drilling and no problems at all... 
all my .TAP files come with only X & Y coords inside the G8x cycles.

I'm talking only about the PostDevTestMachine that is the one actually declared to work well and being thoroughly tested...

**Comment by ReeseWang** [comment]
@vakeiros @teodoryantcheff Oops I was using `Mach3 - 4 axis X.gpp` and didn't notice that line is commented in PostDev.

I thought `Mach3 - 4 axis X.gpp` is bug free.

**Comment by vakeiros** [comment]
@thuSkywalker no problem friend ;)

the PostDevTestMachine is the latest and it has the rotational axis around Y, after this one is cleared as bug free and working 100% (I think it is already but...) it will be available in an over X rotation.
we're developing the over Y first because it's my machine setup, this way I can test everything on my machine in order to clear the bugs. so far so good!

next week I should have the time to make a test part using all kinds of operations using the 4 axis.

**Comment by teodoryantcheff** [comment]
Yeah, as I said above - do pay attention only to PostDevTestMachine.xxx. Ignore the others. PostDev are the only ones that matter.
And also about that Z on drills -- I got confused for a bit. @thuSkywalker and @vakeiros  you are right - it should not be there and also in the current form the post posts correct code.

Cheers,

Teo

**Comment by teodoryantcheff** [comment]
So, since I want to close this PR, let me know your thoughts about tool radius compensation please.

Thanks in advance,

Teo

**Comment by vakeiros** [comment]
Hi Ted,
I don't even know what exactly that is XD

A qui, 21/04/2016, 18:40, teodoryantcheff notifications@github.com
escreveu:

**Comment by teodoryantcheff** [comment]
I do know and honestly think it makes no sense in the context of a cnc post, though let's hear that @thuSkywalker  has to add to this. We may really be missing something here.

**Comment by ReeseWang** [comment]
@teodoryantcheff Sorry for my carelessness. I just heard my boss, who doesn't even know that the CNC has mechanical coordinates and needs home reference at every power up, complaining the tool radius compensation broke his part. I didn't check whether the problem is caused by it, or whether setting tool radius compensation ability to off has any influences on the output G code.

**Pull request closed without merging**
